package agents;

public enum SpecificAction {
	NORDFIRE_TURNLEFT,NORDFIRE_TURNRIGHT, 
	NORD_TURNLEFT, NORD_TURNRIGHT,
	NORDOSTFIRE_TURNLEFT, NORDOSTFIRE_TURNRIGHT,
	NORDOST_TURNLEFT, NORDOST_TURNRIGHT, 
	OSTFIRE_TURNLEFT, OSTFIRE_TURNRIGHT,
	OST_TURNLEFT, OST_TURNRIGHT,
	SUEDOSTFIRE_TURNLEFT, SUEDOSTFIRE_TURNRIGHT, 
	SUEDOST_TURNLEFT, SUEDOST_TURNRIGHT, 
	SUEDFIRE_TURNLEFT, SUEDFIRE_TURNRIGHT, 
	SUED_TURNLEFT, SUED_TURNRIGHT, 
	SUEDWESTFIRE_TURNLEFT, SUEDWESTFIRE_TURNRIGHT,
	SUEDWEST_TURNLEFT, SUEDWEST_TURNRIGHT,
	WESTFIRE_TURNLEFT, WESTFIRE_TURNRIGHT, 
	WEST_TURNLEFT, WEST_TURNRIGHT,
	NORDWESTFIRE_TURNLEFT, NORWESTFIRE_TURNRIGHT, 
	NORDWEST_TURNLEFT, NORDWEST_TURNRIGHT;
}
