package agents;

public enum SpecificAction {
	NORDFIRE, NORD,
	NORDFIRE_TURNLEFT1,NORDFIRE_TURNRIGHT1, 
	NORDFIRE_TURNLEFT2,NORDFIRE_TURNRIGHT2, 
	NORDFIRE_TURNLEFT3,NORDFIRE_TURNRIGHT3, 	
	NORDFIRE_TURNLEFT4,NORDFIRE_TURNRIGHT4,
	
	NORDOSTFIRE, NORDOST,
	NORDOSTFIRE_TURNLEFT1, NORDOSTFIRE_TURNRIGHT1,
	NORDOSTFIRE_TURNLEFT2, NORDOSTFIRE_TURNRIGHT2,
	NORDOSTFIRE_TURNLEFT3, NORDOSTFIRE_TURNRIGHT3,
	NORDOSTFIRE_TURNLEFT4, NORDOSTFIRE_TURNRIGHT4,
	
	OSTFIRE, OST,
	OSTFIRE_TURNLEFT1, OSTFIRE_TURNRIGHT1,
	OSTFIRE_TURNLEFT2, OSTFIRE_TURNRIGHT2,
	OSTFIRE_TURNLEFT3, OSTFIRE_TURNRIGHT3,
	OSTFIRE_TURNLEFT4, OSTFIRE_TURNRIGHT4,
	
	SUEDOSTFIRE, SUEDOST,
	SUEDOSTFIRE_TURNLEFT1, SUEDOSTFIRE_TURNRIGHT1,
	SUEDOSTFIRE_TURNLEFT2, SUEDOSTFIRE_TURNRIGHT2,
	SUEDOSTFIRE_TURNLEFT3, SUEDOSTFIRE_TURNRIGHT3,
	SUEDOSTFIRE_TURNLEFT4, SUEDOSTFIRE_TURNRIGHT4,

	SUEDFIRE, SUED, 
	SUEDFIRE_TURNLEFT1, SUEDFIRE_TURNRIGHT1, 
	SUEDFIRE_TURNLEFT2, SUEDFIRE_TURNRIGHT2, 
	SUEDFIRE_TURNLEFT3, SUEDFIRE_TURNRIGHT3, 
	SUEDFIRE_TURNLEFT4, SUEDFIRE_TURNRIGHT4, 

	SUEDWESTFIRE, SUEDWEST,
	SUEDWESTFIRE_TURNLEFT1, SUEDWESTFIRE_TURNRIGHT1,
	SUEDWESTFIRE_TURNLEFT2, SUEDWESTFIRE_TURNRIGHT2,
	SUEDWESTFIRE_TURNLEFT3, SUEDWESTFIRE_TURNRIGHT3,
	SUEDWESTFIRE_TURNLEFT4, SUEDWESTFIRE_TURNRIGHT4,

	WESTFIRE, WEST, 
	WESTFIRE_TURNLEFT1, WESTFIRE_TURNRIGHT1, 
	WESTFIRE_TURNLEFT2, WESTFIRE_TURNRIGHT2, 
	WESTFIRE_TURNLEFT3, WESTFIRE_TURNRIGHT3, 
	WESTFIRE_TURNLEFT4, WESTFIRE_TURNRIGHT4, 

	NORDWESTFIRE, NORWEST, 
	NORDWESTFIRE_TURNLEFT1, NORDWESTFIRE_TURNRIGHT1, 
	NORDWESTFIRE_TURNLEFT2, NORDWESTFIRE_TURNRIGHT2, 
	NORDWESTFIRE_TURNLEFT3, NORDWESTFIRE_TURNRIGHT3, 
	NORDWESTFIRE_TURNLEFT4, NORDWESTFIRE_TURNRIGHT4, 
}
