package agents;

public enum SpecificAction {
	NORDFIRE, NORDFIRE_TURNLEFT,NORDFIRE_TURNRIGHT, 
	NORD, NORD_TURNLEFT, NORD_TURNRIGHT,
	NORDOSTFIRE, NORDOSTFIRE_TURNLEFT, NORDOSTFIRE_TURNRIGHT,
	NORDOST, NORDOST_TURNLEFT, NORDOST_TURNRIGHT, 
	OSTFIRE, OSTFIRE_TURNLEFT, OSTFIRE_TURNRIGHT,
	OST, OST_TURNLEFT, OST_TURNRIGHT,
	SUEDOSTFIRE, SUEDOSTFIRE_TURNLEFT, SUEDOSTFIRE_TURNRIGHT, 
	SUEDOST, SUEDOST_TURNLEFT, SUEDOST_TURNRIGHT, 
	SUEDFIRE, SUEDFIRE_TURNLEFT, SUEDFIRE_TURNRIGHT, 
	SUED,SUED_TURNLEFT, SUED_TURNRIGHT, 
	SUEDWESTFIRE, SUEDWESTFIRE_TURNLEFT, SUEDWESTFIRE_TURNRIGHT,
	SUEDWEST, SUEDWEST_TURNLEFT, SUEDWEST_TURNRIGHT,
	WESTFIRE,WESTFIRE_TURNLEFT, WESTFIRE_TURNRIGHT, 
	WEST, WEST_TURNLEFT, WEST_TURNRIGHT,
	NORDWESTFIRE, NORDWESTFIRE_TURNLEFT, NORWESTFIRE_TURNRIGHT, 
	NORDWEST, NORDWEST_TURNLEFT, NORDWEST_TURNRIGHT;
}
